name: Kodi Addon-Check

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Kodi addon checker validation
      with:
        kodi-version: matrix
        addon-id: ${{ github.event.repository.name }}
        is-pr: false
